Fix 103 several fixes paym controller
RooftopAcademy/rooftend pull request #104
Opened 2021-11-29 23:11 UTC by agustintosco

## Linked Issue
#103 

## Proposed Changes
- Changed route `payment` to `payment-methods`
- Fixed API example for GET methods
- Changed PUT for PATCH
- Changed return object PaymentMethod for PaymentMethodDto (does not includes id, created_at nor updated_at)

## Evidence

### Documentation

![1](https://user-images.githubusercontent.com/86480738/143956718-db3ac01d-81a7-4fc4-b928-2b8392b3386a.gif)

![2](https://user-images.githubusercontent.com/86480738/143957012-54c69125-f735-4ec2-95be-fdbafedee718.gif)

* Example value for GET methods:

![image](https://user-images.githubusercontent.com/86480738/143957166-52d206be-6bdf-40a5-a51a-ee2a5db6707d.png)

2021-12-14 02:02 UTC, ghnoob commented on src/payment-methods/controllers/payment-method.controller.ts
> +      response.status(404).json({ message: `${error}` });
no me parece buena idea tirar un 404 para cualquier error
yo sacaría el `try/catch` y dejaría que tire un 500.

2021-12-14 13:49 UTC, agustintosco commented on src/payment-methods/controllers/payment-method.controller.ts
> +      if (payment_method) { return payment_method }
dale, lo cambio :+1:

2021-12-14 17:45 UTC, agustintosco commented on src/payment-methods/controllers/payment-method.controller.ts
> +    type: PaymentMethodDto,
Porque devuelve solamente "name" y "type", no toda la entidad. Tengo entendido que una de las formas de hacer eso es con un DTO.

2021-12-14 17:45 UTC, agustintosco commented on src/payment-methods/controllers/payment-method.controller.ts
> +    type: PaymentMethodDto,
Porque devuelve solamente "name" y "type", no toda la entidad. Tengo entendido que una de las formas de hacer eso es con un DTO.

2021-12-14 17:45 UTC, agustintosco commented on src/payment-methods/controllers/payment-method.controller.ts
> +      response.status(404).json({ message: `${error}` });
dale, lo cambio :+1:

2021-12-14 17:51 UTC, ghnoob commented on src/payment-methods/controllers/payment-method.controller.ts
> +    type: PaymentMethodDto,
Pero en el gif que mostras de ejemplo devuelve más campos.
Lo que tenes que hacer es ocultarlos de la respuesta también.

2021-12-14 17:53 UTC, ghnoob commented on src/payment-methods/controllers/payment-method.controller.ts
> +    type: PaymentMethodDto,
Además no devolves realmente el DTO.
Devolvés una objeto de la clase PaymentMethod.
Si no queres que los otros campos aparezcan el la documentación los podes ocultar con `@ApiHideProperty` o no documentarlos directamente

2021-12-15 17:28 UTC, ghnoob commented
Veo que marcaste muchos comentarios como resueltos pero no cambiaste nada. Es por alguna razón en particular?

2021-12-15 17:38 UTC, ghnoob requested changes
Lo único que cambiaría es sacar el id y las fechas de los payment methods que mockeas en los tests porque esos no los devolves en una response real.

2021-12-15 18:17 UTC, agustintosco commented
Ahí estaría, cualquier otra cosa que vean que se me haya pasado me dicen y lo vemos :+1:

2021-12-15 18:36 UTC, ghnoob approved these changes
Creo que está todo bien

2021-12-15 19:56 UTC, Alonso-Pablo approved these changes
¡Se ve todo bien!

2021-12-15 19:56 UTC, pabloroque1 approved these changes

2021-12-15 19:56 UTC, merged