Feature 116 save for later
RooftopAcademy/rooftend pull request #133
Opened 2021-12-08 11:12 UTC by GSaucedoA

### Issue #116 
- Se creo una entidad para la base de datos
- De crearon dto para manejar las respuestas
- se hizo un test basico

#### Pruebas
GET /saved - Este endpoint devuelve correctamente todos los items
![image](https://user-images.githubusercontent.com/77474094/145198056-1c2f1bdd-5820-4051-8db5-df8943e62ca2.png)

POST /saved - Este endpoint agrega correctamente un item
![image](https://user-images.githubusercontent.com/77474094/145198258-d339751f-a22b-4e9b-aeb7-498351344a50.png)

PATCH /saved/{id} - Este endpoint actualiza correctamente el item con el id = {id}
![image](https://user-images.githubusercontent.com/77474094/145198569-b261beca-7f2a-4678-9873-205fd8cf7481.png)

DELETE /saved({id} - este endpoint elimina correctamente el item con el id = {id}
![image](https://user-images.githubusercontent.com/77474094/145198862-4e8d16a6-b62e-4a2d-bcd3-46587dedeffa.png)

2021-12-09 08:51 UTC, ChachoPacho commented
## Evidence
There is not prove that the **POST**, **PATCH** and **DELETE** methods fulfill their functions.

### Required
Show how was the table __before__ and __after__ the __request__, so can be seen that the methods works.

2021-12-14 02:57 UTC, Alonso-Pablo requested changes
Te dejo algunos cambios para hacer...

2021-12-14 02:57 UTC, Alonso-Pablo commented on src/app.module.ts
> +      synchronize: true,
Se descomentó la línea.

2021-12-14 02:57 UTC, Alonso-Pablo commented on src/saved-items/controllers/saved-items.controller.ts
> +        item: { id: 1, itemId: 1, userId: 1, quantity: 1, price: 100 },
El `userId` había dicho el profe que no hay que devolverlo, ni el el GET ni el POST.

2021-12-14 02:57 UTC, Alonso-Pablo commented on src/saved-items/services/saved-items.service.spec.ts
> +});
Esto son los test que se generan automáticamente...
Faltaría hacerlos. :D

2021-12-14 02:57 UTC, Alonso-Pablo commented on src/saved-items/controllers/saved-items.controller.spec.ts
> +});
Esto son los test que se generan automáticamente...
Faltaría hacerlos. :D 
(Este es el video que el profe nos pasó: 
https://www.youtube.com/watch?v=dXOfOgFFKuY )

2021-12-15 23:05 UTC, merged