Feature add payment methods testing
RooftopAcademy/rooftend pull request #138
Opened 2021-12-14 01:01 UTC by agustintosco

## Linked Issue
#137 

## Changes
 - Changed logic when returning values in payment-methods.controller.ts
 - Added testing for payment methods controller
 - Added testing for payment methods service

## Evidence

![image](https://user-images.githubusercontent.com/86480738/145913160-db203ae8-e00f-4ccc-a341-915f96ff2202.png)

2021-12-14 01:48 UTC, ghnoob requested changes

2021-12-14 01:48 UTC, ghnoob commented on src/payment-methods/controllers/payment-method.controller.spec.ts
> +  describe('find', () => {
hace falta probar que devuelve cuando no encuentra el payment method

2021-12-14 01:48 UTC, ghnoob commented on src/payment-methods/controllers/payment-method.controller.ts
> +    }
esto borralo. si no hay payment methods, tendria que devolver un array vacio y no un 404. el 404 es para cuando lo buscas por un id especifico.

2021-12-14 01:48 UTC, ghnoob commented on src/payment-methods/services/payment-method.service.spec.ts
> +  describe('find', () => {
que tendría que devolver cuando no encuentra el método? `undefined`, supongo
falta testear ese caso

2021-12-14 23:00 UTC, agustintosco commented on src/payment-methods/controllers/payment-method.controller.ts
> +    }
Es verdad, lo cambio :+1:

2021-12-15 19:23 UTC, ghnoob requested changes

2021-12-15 19:23 UTC, ghnoob commented on src/payment-methods/controllers/payment-method.controller.spec.ts
> +import { NotFoundError } from 'rxjs';
Borrar esta linea

2021-12-15 19:23 UTC, ghnoob commented on src/payment-methods/models/payment-method.entity.ts
> +import { Exclude, Expose } from 'class-transformer';
el  `Expose` lo sacaría porque no lo estás usando

2021-12-15 19:53 UTC, ghnoob commented
@agustintosco la base de este pr no tendría que ser `fix-103-several-fixes-paym-controller`?

2021-12-15 20:04 UTC, agustintosco commented
Sí, tendría que haber sido fix-103-several-fixes-paym-controller

2021-12-15 20:13 UTC, ghnoob approved these changes
Se arreglaron errores de linting

2021-12-15 20:13 UTC, merged