2021 12 14 address fixes
RooftopAcademy/rooftend pull request #141
Opened 2021-12-14 21:29 UTC by Marcosl14

Create Adress Entity

2021-12-14 22:22 UTC, Alonso-Pablo requested changes
Metiste cambios en el `package-lock.json`, creaste un módulo de `purchases` e hiciste cambios en el módulo de `cart` y `platform`. Todo en el PR para arreglar el módulo de `address`.
¿Dónde quedó la S de SOLID (Responsabilidad Unica)? (?)
Además, falta poner pruebas de que anda y de los tests.

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/addresses/entities/address.entity.ts
> +    example: Date.now(),
¿Esto funciona? ¿Cómo se ve en la documentación? 🤔

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/addresses/entities/address.entity.ts
> +    description: 'Country state name)',
Se te olvidó borrar un paréntesis de cierre acá.

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/addresses/entities/address.entity.ts
> +    description: 'The date when the platform has been soft deleted',
No sé si esto de la documentación lo puede leer las personas que no están en el desarrollo de la app. Pero quedaría medio raro saber que en verdad no están borrando tus datos cuando los querés borrar jajajaja

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/addresses/entities/address.entity.ts
> +    name: 'floor',
Acá se te quedó con el mismo nombre que el de arriba.
En esta columna seria: `office` creo...

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/app.module.ts
> +    PurchasesModule,
Tiene que ir por orden alfabético.
Dejo referencias por si no se recuerda (?)
https://www.rae.es/dpd/abecedario

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/platform/entities/platform.entity.ts
> +    default: () => null,
Estabas arreglando `address` y te metiste en el módulo de `platform` y lo editaste...

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/purchases/controllers/purchases.controller.spec.ts
> +});
Metiste en el mismo PR de arreglos de `address`, tests para el módulo de `purchases`?
Como que tendría que hacerse en PR diferentes...

2021-12-14 22:22 UTC, Alonso-Pablo commented on src/purchases/purchases.module.ts
> +export class PurchasesModule {}
El crear el módulo de `purchases` tendría que ir en otro PR. Lo creas para que funcione `address` y luego lo borras y haces otro PR para meterlo al proyecto... 🤔

2021-12-14 22:26 UTC, ChachoPacho commented on src/app.module.ts
> +    PurchasesModule,
> Tiene que ir por orden alfabético. Dejo referencias por si no se recuerda (?) https://www.rae.es/dpd/abecedario

 Qué malo :crying_cat_face:

2021-12-15 17:48 UTC, Marcosl14 commented
> Metiste cambios en el `package-lock.json`, creaste un módulo de `purchases` e hiciste cambios en el módulo de `cart` y `platform`. Todo en el PR para arreglar el módulo de `address`. ¿Dónde quedó la S de SOLID (Responsabilidad Unica)? (?) Además, falta poner pruebas de que anda y de los tests.

2021-12-15 18:04 UTC, Marcosl14 commented on src/addresses/entities/address.entity.ts
> +    example: Date.now(),
Corregido

2021-12-15 18:04 UTC, Marcosl14 commented on src/addresses/entities/address.entity.ts
> +    description: 'Country state name)',
Corregido

2021-12-15 18:04 UTC, Marcosl14 commented on src/addresses/entities/address.entity.ts
> +    description: 'The date when the platform has been soft deleted',
Corregido

2021-12-15 18:05 UTC, Marcosl14 commented on src/addresses/entities/address.entity.ts
> +    name: 'floor',
corregido

2021-12-15 18:06 UTC, Marcosl14 commented on src/app.module.ts
> +    PurchasesModule,
Corregido. Lo hice en las importaciones, me olvide de hacerlo ahí tambien.

2021-12-15 18:06 UTC, Marcosl14 commented on src/platform/entities/platform.entity.ts
> +    default: () => null,
Si...

2021-12-15 18:07 UTC, Marcosl14 commented on src/purchases/controllers/purchases.controller.spec.ts
> +});
Si...

2021-12-15 18:07 UTC, Marcosl14 commented on src/purchases/purchases.module.ts
> +export class PurchasesModule {}
Ahora ya está... La idea de subir el address era que otro lo pueda continuar.

2021-12-15 18:31 UTC, Bastian1998 commented
El unico cambio que hiciste a cart fue un format no? no veo ningun cambio en la logica @Marcosl14

2021-12-15 18:34 UTC, Marcosl14 commented
> 

No hice cambios a cart en ésta rama.

2021-12-15 23:05 UTC, alezvi approved these changes

2021-12-15 23:05 UTC, merged