Feature message post purchase
RooftopAcademy/rooftend pull request #145
Opened 2021-12-15 19:17 UTC by pabloroque1

Create message post purchase module, Endpoint GET, POST and PATCH.
![Screenshot from 2021-12-15 16-09-34](https://user-images.githubusercontent.com/73512703/146249994-e73445be-d7b8-4ee3-ba4f-5d110707e929.png)

Endpoing GET, has 1 parameter CartId, and return all messages for that purchase.

![Screenshot from 2021-12-15 16-12-40](https://user-images.githubusercontent.com/73512703/146250199-82503ecd-3c69-472b-9d2d-a012851baa78.png)

Endpoint POST only has 4 attributes to create a new message, cart_id, sender_id, message, and date created_at

![Screenshot from 2021-12-15 16-13-51](https://user-images.githubusercontent.com/73512703/146250376-9f1d816e-bfd2-487b-90c9-e658d3ab8d69.png)

Endpoint PATCH only can modified received_at and read at, this is possible using and DTO, updateMessageDTO.

![Screenshot from 2021-12-15 16-15-42](https://user-images.githubusercontent.com/73512703/146250557-abf780a0-19bc-412e-9a59-ec40ce21a9f3.png)

Endpoint DELETE return a forbidden method.

2021-12-15 23:37 UTC, alezvi requested changes

2021-12-15 23:37 UTC, alezvi commented on src/message-post-purchases/services/message-post-purchase.service.ts
> +
Mucho codigo repetido en la funcion anterior.
Si los datos se copian iguales no tiene sentido repetir uno por uno.

```suggestion
       messages = messages.map((item) => {
          return({
            id,
            item
          })
        });
```

2021-12-15 23:37 UTC, alezvi commented on src/message-post-purchases/services/message-post-purchase.service.ts
> +        SELECT * FROM messages_post_purchase
Son realmente necesarios todas las columnas para el frontend ?

2021-12-16 19:51 UTC, ChachoPacho commented on src/users/entities/user.entity.ts
> +import { MessagePostPurchase } from '../../message-post-purchases/entities/message-post-purchase.entity';
Hace un import de `MessagePostPurchase` pero nunca lo implementa o utiliza.

2021-12-16 19:53 UTC, pabloroque1 commented on src/users/entities/user.entity.ts
> +import { MessagePostPurchase } from '../../message-post-purchases/entities/message-post-purchase.entity';
Gracias no me habia dado cuenta, lo voy a modificar

2021-12-18 11:39 UTC, Alonso-Pablo commented
Veo que se modificó y subió el archivo `package-lock.json`. Habría que eliminarlo (y para las próximas no "commitearlo" y "pushearlo") 🤔

2022-01-08 13:59 UTC, pablocanale requested changes
Hacer cambios en la Query

2022-01-08 13:59 UTC, pablocanale commented on src/message-post-purchases/services/message-post-purchase.service.ts
> +        .select("mgp.id")
El id del mensaje y el id del usuario no son necesarios. Si soy el usuario que es dueño de los productos que fueron comprados, me interesaria saber el nombre del item que fue comprado, la cantidad de items, el nombre del usuario que me los compro, cuando fue que realizó la compra. En un mismo carrito podria tener diferentes items de diferentes vendedores, por eso creo que se deberian enviar mensajes individuales por cada item al vendedor que corresponda.

2022-01-13 22:51 UTC, merged