Remove unnecesary shipping methods
RooftopAcademy/rooftend pull request #193
Opened 2022-01-08 15:03 UTC by ChachoPacho

## Summary #183 

- Se borraron los endpoints innecesarios en esta API, y los correspondientes `methods` del sevicio que quedaron innutilzados.
- Se crearon Test para el `controller` y el `service`.
  - Los test del controller no están completamente implementados, pues el controller está incompleto y no tiene respuesta en caso de error.

### Service
<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148649052-2aa8f50c-b414-4d60-ad7e-668d46e513ac.png">
</p>

### Controller
<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148649057-4d123006-04ee-410d-a7bc-a5ca14f0bcbc.png">
</p>

2022-01-08 18:13 UTC, ghnoob requested changes
Como comentario final, no me convence que en los tests uses tanto el expect.any.
Yo comprobaría que los valores sean realmente los que se esperan, no solamente el tipo.

2022-01-08 18:13 UTC, ghnoob commented on src/shipping-methods/services/shipping-methods.service.ts
>      //return this.shippingMethodsRepo.find();
se que esto no lo hiciste vos, pero deja lo que esta comentado y saca los valores que están harcodeados aca en el serivicio

2022-01-08 18:13 UTC, ghnoob commented on src/shipping-methods/controllers/shipping-methods.controller.spec.ts
> +    getCount: jest.fn().mockImplementation(() => Promise.resolve(1)),
aca estás mockeand len realiddad los metodos del controlador y no los del repositorio, que son solamente `find` y `findOne`. Los tests siguen pasando porque en realidad el repositorionunca esta usando el repositorio, lo que me lleva al próximo comentario.

2022-01-09 15:39 UTC, ChachoPacho commented
@ghnoob creo haber cumplido con lo que pediste en la review.

- Removí los `expect.any` y puse valores literales para estar seguros.
-  En `controller` corregí el nombre del mock que hice.
- En `service`, implementé correctamente un mock del repositorio.

### Controller
<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148689270-0ca75aaf-1d4c-477d-85a3-9388abf2a20d.png">
</p>

### Service
<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148689266-2a8f0119-9cc4-4b9f-ab50-cde5488f9c67.png">
</p>

2022-01-10 11:48 UTC, ghnoob requested changes

2022-01-10 11:48 UTC, ghnoob commented on src/shipping-methods/controllers/shipping-methods.controller.ts
> +  getOne(@Param('id') id: number) {
podria devolver un 404 cuando no encuentra el método

2022-01-10 18:45 UTC, ChachoPacho commented on src/shipping-methods/controllers/shipping-methods.controller.ts
> +  getOne(@Param('id') id: number) {
> podria devolver un 404 cuando no encuentra el método

# Test

## Service

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148821000-dcb58f2e-d67b-409e-94e7-fb2bb842fc0a.png">
</p>

## Controller

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148821030-303298fc-bbd4-45cb-bd7f-bb28f4e18a7e.png">
</p>

# Example 

## Successful

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148821062-6dcd98ba-4b82-4553-b0dc-36780ca35e56.png">
</p>

## Failure

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/148821069-d47fe781-ce4c-45f9-a204-9d326d0153a5.png">
</p>

> Pd: @ghnoob aprobá el PR, por favor.

2022-01-10 19:18 UTC, ghnoob approved these changes
La proxima podes pedirme review de vuelta en vez de mencionarme.
Lo mergeo despueś de la clase.

2022-01-11 00:57 UTC, merged