Auth custom messages
RooftopAcademy/rooftend pull request #205
Opened 2022-01-12 19:21 UTC by ChachoPacho

Solves #185 

- Error 403 Documentado en los casos de `GET /:id`, `PATCH`, `DELETE`. Los demás casos me parecieron incoherentes. 
- Error 404 Documentado en `GET /:id` y `PATCH`.
- Tests funcionando.
- `Guard`s implementados en `GET /:id`, `PATCH`, `DELETE`. Los demás casos me parecieron innecesarios. 

## Test
### Controller
<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149207252-965f8390-1ddd-49cb-ae48-6b54789added.png">
</p>

### Service
<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149207258-a0b59672-2626-41a1-afd8-7dbd98c35f56.png">
</p>

2022-01-12 23:08 UTC, ghnoob requested changes
Podrías implementar lo de authorizacion aca que ya quedo en nuestra rama primero? Y a lo que es autorizacion hacelo desde el controller y no desde el service como dijo ale

2022-01-14 02:44 UTC, ChachoPacho commented
- Autorización se pasó de `Service` a `Controller`.
- Autenticación fue implementado.

# Tests
## Service
- Se quitaron los `ForbiddenException`

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441669-16440ea2-e915-442e-9c80-21f218318590.png">
</p>

## Controller
- Se añadieron los `ForbiddenException`

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441681-efd790fd-719a-4dc6-995e-967414ab31ce.png">
</p>


# Examples
## Token

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149442017-bb54551a-4775-4f5e-b367-45167919f337.png">
</p>

## Routes
### `GET`
> La búsqueda se realiza en base al `id` del `user`, por lo que nunca se devolveran `CustomMessages` ajenos. 

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441861-af51effc-ab5b-4286-bde9-4e525b79e0fa.png">
</p>

### `GET /:id`
#### A `CustomMessage` propio

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441866-037f6026-84de-4b3a-b5de-7624da261161.png">
</p>

#### A `CustomMessage` ajeno

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441873-69253879-ea79-4514-be40-9e68ad200244.png">
</p>

### `POST`, `DELETE` y `PATCH`
#### `POST`

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441871-484fd268-947e-468e-9358-3ed10e1daf88.png">
</p>

#### `DELETE`

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441874-ddb4a176-5b01-4894-a3bb-8e28aee5db73.png">
</p>

#### `PATCH`

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441880-c6ab6ee5-05ac-4aeb-bc60-83b777322c80.png">
</p>

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149441877-344c8788-67e1-4ef4-b5f6-570d7a61131e.png">
</p>

## Credenciales Inválidas

![2022-01-13_23-28](https://user-images.githubusercontent.com/76873353/149441883-b10a54eb-2b62-4d72-ba07-fcf096af4963.png)

2022-01-14 14:00 UTC, ghnoob requested changes
Faltaria mergear main, sacar el `result` y comprobar que todo funcione bien

2022-01-14 14:00 UTC, ghnoob commented on src/custom-messages/controllers/custom-messages.controller.ts
> +      throw new ForbiddenException();
aca trendrias que usar el  `failIfCanNotAccess` que creaste

2022-01-14 14:00 UTC, ghnoob commented on src/custom-messages/controllers/custom-messages.controller.ts
> +  private async failIfCanNotAccess(
pequeña sugerencia de ortografia que queda a tu gusto: si bien "can not" como dos palabras es valido en inglés, escribir "cannot" como una sola palabra es mucho mas comun por lo que yo pondria la n en minuscula

2022-01-14 14:00 UTC, ghnoob commented on src/custom-messages/entities/update-custom-messages.dto.ts
>  }
si este dto es el mismo que el de creacion pero con los valores opcionales, lo podes reemplazar por
```ts
import { PartialType } from '@nestjs/swagger';
import { CreateCustomMessageDTO } from './create-custom-message.dto'

export class UpdateCustomMessageDTO extends PartialType(CreateCustomMessageDTO) {} 
```
[fuente](https://docs.nestjs.com/openapi/mapped-types#partial)

2022-01-14 14:00 UTC, ghnoob commented on src/custom-messages/services/custom-messages.service.ts
> +    return this.CustomMessageRepo.find({ user });
cambiar por
```ts
return this.CustomMessageRepo.find({ user: { id: user.id } });
```

2022-01-14 15:23 UTC, ChachoPacho commented on src/custom-messages/controllers/custom-messages.controller.ts
> +      throw new ForbiddenException();
Es que no quiero que se devuelva un error 404 en caso de que no se encuentre el `CustomMessage`.

2022-01-14 16:48 UTC, ChachoPacho commented
- Cambios en `UpdateCustomMessageDTO`
- Implementación de `@ApiBearerAuth()`
- Uso de `failIfCannotAccess` en Delete del `Controller`
- Cambios en la query de `findAll` del `Service`
- Se borró el `.result` del `User` traido del `Request`
- Actualización de los tests en torno a todo lo anterior

# Test

<p align="center">
<img src="https://user-images.githubusercontent.com/76873353/149553090-da3c0df9-c4dd-49dc-83aa-e7b17be45288.png">
</p>

2022-01-14 18:32 UTC, ghnoob requested changes
Tambien agregaria el `@ApiBody` en el post y el patch

2022-01-14 18:32 UTC, ghnoob commented on src/custom-messages/controllers/custom-messages.controller.ts
> +    this.failIfCannotAccess(Permission.Delete, user, id);
falta esperar este metodo

2022-01-14 19:04 UTC, ChachoPacho commented
Ya me cansé de sacar fotitos, juro que todo funciona :D.
> Testeado manualmente por mí en la [API](http://localhost:3000/api/#/Custom%20Messages)

2022-01-14 19:22 UTC, ghnoob approved these changes

2022-01-14 19:23 UTC, merged