2022 01 19 refactor auth add mail
RooftopAcademy/rooftend pull request #245
Opened 2022-01-20 17:23 UTC by agustintosco

## Linked Issue
No linked issue

## Proposed Changes
- Added and configured MailerModule.
- Added mail module, service, constants and template for sending email confirmation.
- Added updateAccountStatus to authorization service.
- Added confirm-user endpoint in authentication controller.

## Evidence

**User registration**

![1](https://user-images.githubusercontent.com/86480738/150389170-889605fe-faeb-49dc-9860-5505c891a9dd.gif)

**Email received with link to confirm user**

![2](https://user-images.githubusercontent.com/86480738/150389208-dc519771-2f7a-401e-9402-4916fadf49e0.gif)

**User was created with account status = 2, meaning is PENDING**

![image](https://user-images.githubusercontent.com/86480738/150389397-f335c628-e5b7-47e8-bc71-c376af0f2dfe.png)

![3](https://user-images.githubusercontent.com/86480738/150389290-7f2b78bc-240c-40a9-a26b-c1dfc38eb509.gif)

**User confirmation through confirm-user endpoint**

![4](https://user-images.githubusercontent.com/86480738/150389468-52609c87-9825-4817-b33b-bac502c8c495.gif)

**Checking that account status changed to 3, meaning that account status now is ACTIVE**

![image](https://user-images.githubusercontent.com/86480738/150389397-f335c628-e5b7-47e8-bc71-c376af0f2dfe.png)

![5](https://user-images.githubusercontent.com/86480738/150389543-f61fcb6a-fe89-4fd1-82e0-33b0e13777b9.gif)

2022-01-20 17:46 UTC, FabioTrucco requested changes

2022-01-20 17:46 UTC, FabioTrucco commented on src/users/services/user.service.ts
> +     *
el updateAccountStatus no está implementado

2022-01-20 17:54 UTC, agustintosco commented on src/users/services/user.service.ts
> +     *
Fabio como vimos esto está implementado en un commit posterior

2022-01-20 22:38 UTC, Alonso-Pablo commented on src/authentication/controllers/authentication.controller.ts
> +    status: 204,
Esto sería un 200, diciendo que todo salió bien.

2022-01-20 22:40 UTC, Alonso-Pablo commented on src/authentication/controllers/authentication.controller.ts
>      status: 409,
Faltaría un `schema: { example: { ...` y el mensaje que aparecería en caso de que esté `Forbbiden`

2022-01-20 22:43 UTC, Alonso-Pablo requested changes
Algunos cambios...

2022-01-20 22:43 UTC, Alonso-Pablo commented on src/authentication/controllers/authentication.controller.ts
> +    status: 403,
Faltaría un `schema: { example: { ...` y el mensaje que aparecería en caso de que esté `Forbidden`

2022-01-20 22:43 UTC, Alonso-Pablo commented on src/authentication/services/authentication.service.ts
> +    console.log(user.account_status)
Acá se te olvido un `console.log` equisde.

2022-01-20 22:43 UTC, Alonso-Pablo commented on src/mail/mail.module.ts
> +        // or
Se podría ir borrando los comentarios. Parecería que hubiesen hecho copy-paste... 🤔

2022-01-21 18:21 UTC, FabioTrucco requested changes

2022-01-21 18:21 UTC, FabioTrucco commented on src/authentication/services/authentication.service.ts
>      if (user.account_status != AccountStatusesEnum.ACTIVE) {
Primero habría que checkear que exista el usuario (invertir los if)

2022-01-21 18:25 UTC, FabioTrucco commented
Recién veo que en el servicio de authentication el método create devuelve un newUser que ya no lo usamos. Habría hacerlo void al create borrando el return

2022-01-21 19:46 UTC, Marcosl14 approved these changes

2022-01-21 19:48 UTC, merged